docker:
  image: "sfount/bhima:latest"
architect:
- sfount
install:
- sudo service mysql start
- npm install 
- bower install
assets:
  .env.production: "sfount/sfount-bhima-assets#.env.production"
  .env.development: "sfount/sfount-bhima-assets#.env.development"
  .env.staging: "sfount/sfount-bhima-assets#.env.staging"
merge: 
  script: |-
    echo "Building..."
    ./node_modules/.bin/gulp build
    echo "Testing build..."
    ./sh/integration-tests.sh
    export DISPLAY=:99
    ./sh/test-ends.sh
    echo "Complete (more tests to follow)..."
