docker:
  image: "sfount/bhima:latest"
architect:
- sfount
install:
- cp /home/r/.env.production /home/r/repo/
- cp /home/r/.env.development /home/r/repo/
- cp /home/r/.env.staging /home/r/repo/
- sudo /usr/bin/Xvfb :99 -ac -screen 0 1024x768x24 &
- sudo service mysql start
- npm install 
- bower install
- node node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update
assets:
  .env.production: "sfount/sfount-bhima-assets#.env.production"
  .env.development: "sfount/sfount-bhima-assets#.env.development"
  .env.staging: "sfount/sfount-bhima-assets#.env.staging"
merge: 
  script: |-
    echo "Setting up ENV..."
    export $(sed -e '/^#/d' .env.development | xargs)
    ./sh/install.sh
    echo "Building..."
    ./node_modules/.bin/gulp build
    echo "Testing build..."
    ./sh/integration-tests.sh
    export DISPLAY=:99
    ./sh/test-ends.sh
    echo "Complete (more tests to follow)..."
