docker:
  as_root: true
  image: "sfount/bhima:latest"
architect:
- sfount
install:
- cp /home/r/.env.production /home/r/repo/
- cp /home/r/.env.development /home/r/repo/
- cp /home/r/.env.staging /home/r/repo/
- sudo service mysql start
- npm install 
- bower install --allow-root
assets:
  .env.production: "sfount/sfount-bhima-assets#.env.production"
  .env.development: "sfount/sfount-bhima-assets#.env.development"
  .env.staging: "sfount/sfount-bhima-assets#.env.staging"
merge: 
  script: |-
    echo "Setting up ENV..."
    /bin/bash /opt/dependencies.sh
    export CHROME_USER_DATA_DIR=/root/.config/google-chrome/
    export DISPLAY=:99
    export $(sed -e '/^#/d' .env.development | xargs)
    ./sh/install.sh
    echo "Building..."
    echo "Running integration tests..."
    ./sh/integration-tests.sh
    sleep 60
    echo "Setting up end to end tests..."
    ./sh/test-ends.sh
    echo "Complete (more tests to follow)..."
